services:
  - type: web
    name: mizani-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: FUJI_RPC_URL
        value: https://api.avax-test.network/ext/bc/C/rpc
      - key: PAYMENT_LOG_ADDRESS
        value: 0xa786fEB386e44F13bE7bA33A1EEf28CCbcFb2Eef
      - key: CORS_ORIGIN
        value: ${RENDER_EXTERNAL_HOSTNAME}
    autoDeploy: true